language: node_js
node_js:
- '11.2.0'
os:
- osx
osx_image: xcode11.2
cache:
    directories:
        - "$HOME/.npm"
jobs:
    include:
        - if: branch = master
          install:
            - npm install
            - sh .travis.certificate.sh
          script:
            - npm run move-ui-production
            - npm run bundle
            - npm run sign
            - npm run package:notarize
            - npm run publish:darwin
        - if: branch = develop OR branch =~ ^feature
          install:
            - npm install
            - git clone https://github.com/strawbees/code-ui.git
            - cd code-ui
            - git checkout develop
            - npm install
            - npm link
            - cd ..
            - npm link "@strawbees/code-ui"
            - sh .travis.certificate.sh
          script:
            - export CONFIG=desktop_stage
            - npm run build-ui
            - npm run move-ui-develop
            - export NODE_ENV=stage
            - npm run bundle
            - npm run sign
            - npm run package:notarize
            - npm run publish:darwin
