language: node_js
node_js:
- '11.2.0'
os:
- osx
install:
- npm ci --only=production
cache:
  directories:
  - "$HOME/.npm"
script:
- npm run build
branches:
  only:
    - master
    - develop
    - feature/macos-build
addons:
  artifacts:
    paths: ./dist/versions
    debug: true
