language: node_js
node_js:
- '11.2.0'
os:
- osx
cache:
    directories:
        - "$HOME/.npm"
jobs:
    include:
        - if: branch = master
          install:
            - npm install --only=production
          script:
            - npm run move-ui-production
            - NODE_ENV=production npm run build
        - if: branch = develop OR branch =~ ^feature
          install:
            - npm install
            - git clone https://github.com/strawbees/code-ui.git
            - cd code-ui
            - git checkout develop
            - npm install
            - npm link
            - cd ..
            - npm link "@strawbees/code-ui"
          script:
            - CONFIG=desktop_stage npm run build-ui
            - npm run move-ui-develop
            - NODE_ENV=stage npm run build

addons:
  artifacts:
    paths: ./dist/versions
    debug: true
