environment:
  nodejs_version: 11.0.0

platform:
  - x86
  - x64

init:
  - ps: Install-Product node $env:nodejs_version $env:platform
  - cmd: cinst -y nsis
  - cmd: SET PATH=C:\Program Files\NSIS\;C:\Program Files (x86)\NSIS\;%PATH%

# defined specific build configs for different branches
for:
-
  branches:
    only:
      - master
  environment:
    NODE_ENV: production
  install:
    - cmd: npm install --only=production
  build_script:
    - cmd: npm run move-ui-production
    - cmd: npm run bundle
    - cmd: npm run package:only
-
  branches:
    only:
      - develop
      - /feature*/
  environment:
    NODE_ENV: stage
  install:
    - cmd: npm install --only=production
    - cmd: git clone https://github.com/strawbees/code-ui.git
    - cmd: cd code-ui
    - cmd: git checkout develop
    - cmd: npm install
    - cmd: npm link
    - cmd: cd %APPVEYOR_BUILD_FOLDER%
    - cmd: npm link "@strawbees/code-ui"
  build_script:
    - cmd: set CONFIG=desktop_stage
    - cmd: npm run build-ui
    - cmd: npm run move-ui-develop
    - cmd: npm run bundle
    - cmd: npm run package:only

artifacts:
  - path: dist\versions\**\*
    name: build

version: "{build}"

skip_tags: true
