environment:
  nodejs_version: 11.0.0

platform:
  - x86
  - x64

install:
  - ps: Install-Product node $env:nodejs_version $env:platform
  - cinst -y nsis
  - SET PATH=C:\Program Files\NSIS\;C:\Program Files (x86)\NSIS\;%PATH%
  - npm ci --only=production

# defined specific build configs for different branches
for:
-
  branches:
    only:
      - master
  environment:
    NODE_ENV: production
  install:
    - cmd: npm ci --production
  build_script:
    - cmd: npm run move-ui-production
    - cmd: npm run bundle
    - cmd: npm run package
-
  branches:
    only:
      - develop
  environment:
    NODE_ENV: stage
  install:
      - cmd: git clone --single-branch --branch develop https://github.com/strawbees/code-ui.git
      - cmd: cd code-ui
      - cmd: npm link
      - cmd: cd ..
      - cmd: npm ci --production
  build_script:
    - cmd: set CONFIG=web_stage
    - cmd: npm run build-ui
    - cmd: npm run move-ui-develop
    - cmd: npm run bundle
    - cmd: npm run package
-
  branches:
    only:
      - /feature*/
  environment:
    NODE_ENV: stage
  build_script:
    - cmd: npm install
    - cmd: npm run move-ui-stage
    - cmd: npm run bundle
    - cmd: npm run package

artifacts:
  - path: dist\versions\**\*
    name: build

version: "{build}"

skip_tags: true
